version: 2.1

orbs:
  python: circleci/python@2.1.1

workflows:
  build-and-test:
    jobs:
      - build-and-test

jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.10.5
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Run tests
          command: export COVERALLS_REPO_TOKEN=wOkEkKevT07xwMLkJYs51tzmFHLb0mPZO && pytest && pylint app.py && pylint bmi_calculator.py && coveralls
